"use client";

import { useMemo, useState } from "react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Calculator, Copy, Landmark, Plus, Printer, Save, Trash2 } from "lucide-react";
import { z } from "zod";
import { calculateCredit, calculateMonthlyRate } from "@/lib/calculations/financial";
import { deleteSimulation, loadSimulations, saveSimulation } from "@/lib/storage/simulations";
import { dateMonthsAgo, money, uid } from "@/lib/utils";
import type { Creditor, CreditorType, Obligation, Simulation } from "@/types";

const obligationSchema = z.object({ originalPrincipal: z.number().positive("El capital debe ser mayor a cero"), interestRate: z.number().min(0), originalTermMonths: z.number().int().positive("El plazo debe ser mayor a cero") });
const colors = ["#0e7490", "#0284c7", "#7c3aed", "#db2777", "#ea580c", "#65a30d"];
const blankObligation = (creditorId: string): Obligation => ({ id: uid(), creditorId, name: "Nueva obligación", type: "creditoConsumo", originalPrincipal: undefined, disbursementDate: dateMonthsAgo(12), originalTermMonths: undefined, interestRate: undefined, interestRateType: "effectiveAnnual", amortizationSystem: "fixedPayment", paymentMode: "total", totalPaid: undefined, payments: [], installmentsPaid: 0, reportedBalance: undefined, reportedOrdinaryInterest: undefined, reportedDefaultInterest: undefined, reportedOtherCharges: undefined, daysPastDue: 0, hasGuarantee: false, hasLegalCollection: false });
const newSimulation = (): Simulation => ({ id: uid(), title: "Nueva simulación", cutoffDate: new Date().toISOString().slice(0, 10), creditors: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });

function Numeric({ value, onChange, label, placeholder = "0" }: { value?: number; onChange: (value?: number) => void; label: string; placeholder?: string }) { return <label className="field"><span>{label}</span><input inputMode="decimal" value={value ?? ""} onChange={(e) => onChange(e.target.value === "" ? undefined : Number(e.target.value.replace(/[^0-9.-]/g, "")))} placeholder={placeholder} /></label>; }

export function Dashboard() {
  const [simulation, setSimulation] = useState<Simulation>(() => newSimulation()); const [saved, setSaved] = useState<Simulation[]>(() => typeof window === "undefined" ? [] : loadSimulations()); const [addNotice, setAddNotice] = useState(""); const [monthlyBudget, setMonthlyBudget] = useState(2000000); const [discount, setDiscount] = useState(20); const [includeFutureInterest, setIncludeFutureInterest] = useState(false); const [notice, setNotice] = useState("");
  const calculations = useMemo(() => simulation.creditors.flatMap((c) => c.obligations.map((o) => ({ creditor: c, obligation: o, calculation: calculateCredit(o) }))), [simulation]);
  const totals = useMemo(() => calculations.reduce((a, x) => ({ original: a.original + x.calculation.originalPrincipal, principal: a.principal + x.calculation.principalOutstanding, interest: a.interest + x.calculation.ordinaryInterest, defaultInterest: a.defaultInterest + x.calculation.defaultInterest, other: a.other + x.calculation.otherCharges, reported: a.reported + (x.calculation.reportedBalance ?? 0), estimated: a.estimated + x.calculation.calculatedBalance }), { original: 0, principal: 0, interest: 0, defaultInterest: 0, other: 0, reported: 0, estimated: 0 }), [calculations]);
  const selectedBalance = totals.reported || totals.estimated; const monthlyRate = calculations.length ? calculations.reduce((sum, x) => sum + (x.obligation.interestRate ? calculateMonthlyRate(x.obligation.interestRate, x.obligation.interestRateType ?? "effectiveAnnual") : 0), 0) / calculations.length : 0;
  const paymentMonths = monthlyBudget > 0 ? (includeFutureInterest && monthlyRate > 0 ? Math.ceil(Math.log(monthlyBudget / (monthlyBudget - selectedBalance * monthlyRate)) / Math.log(1 + monthlyRate)) : Math.ceil(selectedBalance / monthlyBudget)) : 0;
  const update = (fn: (s: Simulation) => Simulation) => setSimulation((s) => ({ ...fn(s), updatedAt: new Date().toISOString() }));
  const addCreditor = () => { const id = uid(); update((s) => ({ ...s, creditors: [...s.creditors, { id, name: "", type: "banco", obligations: [blankObligation(id)] }] })); setAddNotice("Acreedor agregado. Escriba su nombre y los datos de la deuda."); setTimeout(() => { const el = document.getElementById(`creditor-${id}`); el?.focus(); el?.scrollIntoView({ behavior: "smooth", block: "center" }); }, 50); };
  const removeCreditor = (id: string) => update((s) => ({ ...s, creditors: s.creditors.filter((c) => c.id !== id) }));
  const changeCreditor = (id: string, patch: Partial<Creditor>) => update((s) => ({ ...s, creditors: s.creditors.map((c) => c.id === id ? { ...c, ...patch } : c) }));
  const addObligation = (creditorId: string) => update((s) => ({ ...s, creditors: s.creditors.map((c) => c.id === creditorId ? { ...c, obligations: [...c.obligations, blankObligation(creditorId)] } : c) }));
  const changeObligation = (creditorId: string, id: string, patch: Partial<Obligation>) => update((s) => ({ ...s, creditors: s.creditors.map((c) => c.id === creditorId ? { ...c, obligations: c.obligations.map((o) => o.id === id ? { ...o, ...patch } : o) } : c) }));
  const removeObligation = (creditorId: string, id: string) => update((s) => ({ ...s, creditors: s.creditors.map((c) => c.id === creditorId ? { ...c, obligations: c.obligations.filter((o) => o.id !== id) } : c) }));
  const save = () => { saveSimulation(simulation); setSaved(loadSimulations()); setNotice("Simulación guardada en este dispositivo."); };
  const load = (s: Simulation) => { setSimulation(s); setNotice("Simulación abierta."); };
  const duplicate = (s: Simulation) => { const copy = { ...s, id: uid(), title: `${s.title} (copia)`, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; saveSimulation(copy); setSaved(loadSimulations()); };
  const loadExample = () => { const id = uid(); const creditor: Creditor = { id, name: "Banco Andino", type: "banco", obligations: [{ ...blankObligation(id), name: "Crédito libre inversión", originalPrincipal: 100000000, interestRate: 18, originalTermMonths: 60, installmentsPaid: 20, totalPaid: 40000000, reportedBalance: 75000000 }, { ...blankObligation(id), name: "Tarjeta de crédito", type: "tarjetaCredito", originalPrincipal: 8000000, reportedBalance: 9200000, amortizationSystem: "custom" }] }; setSimulation({ ...newSimulation(), title: "Ejemplo · Banco Andino", creditors: [creditor] }); };
  const composition = [{ name: "Capital", value: totals.principal }, { name: "Intereses", value: totals.interest }, { name: "Mora", value: totals.defaultInterest }, { name: "Otros", value: totals.other }].filter((x) => x.value > 0);
  const creditorData = simulation.creditors.map((c) => ({ name: c.name || "Sin nombre", saldo: calculations.filter((x) => x.creditor.id === c.id).reduce((s, x) => s + x.calculation.calculatedBalance, 0) }));
  return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="shell flex items-center justify-between py-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-700 text-white"><Calculator size={21}/></div><div><h1 className="text-lg font-bold tracking-tight">Calculadora de Insolvencia</h1><p className="text-xs text-slate-500">Colombia · simulación financiera</p></div></div><button className="button secondary no-print" onClick={() => window.print()}><Printer size={16}/> Imprimir</button></div></header>
  <div className="shell py-8"><section className="rounded-2xl bg-gradient-to-br from-slate-950 to-cyan-950 p-7 text-white shadow-xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-medium text-cyan-200">SIMULACIÓN PRIVADA · SIN SERVIDOR</p><h2 className="text-3xl font-bold tracking-tight">Reconstruye obligaciones.<br/>Evalúa escenarios.</h2><p className="mt-3 max-w-xl text-sm text-slate-300">Los datos permanecen en este dispositivo. Los resultados son matemáticos y no constituyen una conclusión jurídica.</p></div><button className="button light no-print" onClick={loadExample}>Cargar ejemplo</button></div></section>
  <section className="stats-grid mt-6"><Stat label="Acreedores" value={simulation.creditors.length.toString()}/><Stat label="Obligaciones" value={calculations.length.toString()}/><Stat label="Pasivo estimado" value={money(totals.estimated)}/><Stat label="Capital pendiente" value={money(totals.principal)}/></section>
  <div className="mt-8 grid gap-8 lg:grid-cols-[1.3fr_.7fr]"><section><div className="section-heading"><div><p className="eyebrow">PASO 1 · 2</p><h2>Acreedores y obligaciones</h2></div><button className="button no-print" onClick={addCreditor}><Plus size={16}/> Agregar acreedor</button></div>
  {addNotice && <p className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800 no-print">{addNotice}</p>}
  {simulation.creditors.length === 0 && <div className="empty"><Landmark size={30}/><h3>Aún no hay acreedores</h3><p>Pulse el botón azul &quot;Agregar acreedor&quot; para empezar.</p></div>}
  <div className="space-y-4">{simulation.creditors.map((creditor) => <article key={creditor.id} className="card"><div className="flex flex-wrap items-end gap-3 border-b border-slate-100 pb-4"><label className="field min-w-50 flex-1"><span>Nombre del acreedor</span><input id={`creditor-${creditor.id}`} placeholder="Ej. Banco X" value={creditor.name} onChange={(e) => changeCreditor(creditor.id, { name: e.target.value })}/></label><select value={creditor.type} onChange={(e) => changeCreditor(creditor.id, { type: e.target.value as CreditorType })}><option value="banco">Banco</option><option value="cooperativa">Cooperativa</option><option value="entidadFinanciera">Entidad financiera</option><option value="particular">Particular</option><option value="empresa">Empresa</option><option value="entidadPublica">Entidad pública</option><option value="otro">Otro</option></select><button className="icon-button ml-auto no-print" aria-label="Eliminar acreedor" onClick={() => removeCreditor(creditor.id)}><Trash2 size={16}/></button></div>
  <div className="mt-4 space-y-3">{creditor.obligations.map((o) => <ObligationEditor key={o.id} obligation={o} onChange={(patch) => changeObligation(creditor.id, o.id, patch)} onRemove={() => removeObligation(creditor.id, o.id)}/>)}</div><button className="button mt-4 w-full no-print" onClick={() => addObligation(creditor.id)}><Plus size={16}/> Agregar otra deuda de este acreedor</button></article>)}</div></section>
  <aside className="space-y-6"><section className="card sticky top-5"><p className="eyebrow">PASO 3 · 4</p><h2 className="mb-5 text-xl font-bold">Consolidado global</h2><Breakdown label="Capital original" value={totals.original}/><Breakdown label="Capital pendiente" value={totals.principal}/><Breakdown label="Intereses corrientes" value={totals.interest}/><Breakdown label="Intereses de mora" value={totals.defaultInterest}/><Breakdown label="Otros conceptos" value={totals.other}/><div className="mt-4 rounded-xl bg-cyan-50 p-4"><p className="text-xs font-semibold text-cyan-700">SALDO MATEMÁTICO ESTIMADO</p><p className="mt-1 text-2xl font-bold text-cyan-950">{money(totals.estimated)}</p></div>{totals.reported > 0 && <div className="mt-3 border-t pt-3 text-sm"><p className="text-slate-500">Saldo informado</p><p className="font-semibold">{money(totals.reported)}</p><p className="mt-1 text-xs text-amber-700">Diferencia: {money(totals.reported - totals.estimated)}. Verifique contrato, estado de cuenta e historial de pagos.</p></div>}</section></aside></div>
  {calculations.length > 0 && <section className="mt-10"><div className="section-heading"><div><p className="eyebrow">PASO 5</p><h2>Simula tu escenario</h2></div></div><div className="grid gap-5 lg:grid-cols-3"><section className="card"><p className="text-sm font-semibold">Escenarios de pago</p><div className="scenario"><span>Saldo completo</span><strong>{money(selectedBalance)}</strong></div><div className="scenario"><span>Capital pendiente</span><strong>{money(totals.principal)}</strong><small>Escenario matemático de referencia.</small></div><label className="field mt-4"><span>Descuento hipotético (%)</span><input type="number" min="0" max="100" value={discount} onChange={(e) => setDiscount(Number(e.target.value))}/></label><div className="scenario"><span>Con descuento</span><strong>{money(selectedBalance * (1 - discount / 100))}</strong><small>No implica obligación del acreedor.</small></div></section><section className="card"><p className="text-sm font-semibold">Pago mensual global</p><Numeric label="Presupuesto mensual" value={monthlyBudget} onChange={(v) => setMonthlyBudget(v || 0)}/><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={includeFutureInterest} onChange={(e) => setIncludeFutureInterest(e.target.checked)}/> Calcular intereses futuros</label><div className="scenario"><span>Plazo estimado</span><strong>{Number.isFinite(paymentMonths) ? `${paymentMonths} meses` : "Pago insuficiente"}</strong></div><p className="mt-3 text-xs text-slate-500">La distribución proporcional entre obligaciones es solo un escenario financiero.</p></section><section className="card"><p className="text-sm font-semibold">Composición del pasivo</p>{composition.length > 0 ? <div className="h-52"><ResponsiveContainer><PieChart><Pie data={composition} dataKey="value" nameKey="name" innerRadius={50} outerRadius={77}>{composition.map((_, i) => <Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip formatter={(v) => money(Number(v))}/></PieChart></ResponsiveContainer></div> : <p className="mt-6 text-sm text-slate-500">Completa los datos para ver el gráfico.</p>}</section></div>
  {creditorData.length > 1 && <section className="card mt-5"><p className="mb-4 text-sm font-semibold">Distribución por acreedor</p><div className="h-64"><ResponsiveContainer><BarChart data={creditorData}><XAxis dataKey="name" tick={{fontSize: 11}}/><YAxis tickFormatter={(v) => `${Math.round(v / 1e6)}M`} tick={{fontSize: 11}}/><Tooltip formatter={(v) => money(Number(v))}/><Bar dataKey="saldo" fill="#0e7490" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section>}</section>}
  <section className="mt-10 rounded-2xl border border-cyan-100 bg-cyan-50 p-5"><h2 className="font-bold text-cyan-950">Revisión jurídica necesaria</h2><p className="mt-1 text-sm text-cyan-900">La simulación no decide la procedencia del trámite, prelación, validez de cobros, tratamiento de garantías ni efectos jurídicos de intereses. Es necesario verificar documentos y la normativa aplicable.</p></section>
  <section className="no-print mt-8 border-t border-slate-200 pt-7"><div className="flex flex-wrap items-center gap-3"><button className="button" onClick={save}><Save size={16}/> Guardar simulación</button><button className="button secondary" onClick={() => { setSimulation(newSimulation()); setNotice("Nueva simulación creada."); }}><Plus size={16}/> Nueva</button>{notice && <span className="text-sm text-emerald-700">{notice}</span>}</div>{saved.length > 0 && <div className="mt-5"><p className="mb-2 text-sm font-semibold">Guardadas en este dispositivo</p><div className="flex flex-wrap gap-2">{saved.map((s) => <div key={s.id} className="saved"><button onClick={() => load(s)}>{s.title}</button><button aria-label="Duplicar" onClick={() => duplicate(s)}><Copy size={14}/></button><button aria-label="Eliminar" onClick={() => { deleteSimulation(s.id); setSaved(loadSimulations()); }}><Trash2 size={14}/></button></div>)}</div></div>}</section></div></main>;
}

function ObligationEditor({ obligation: o, onChange, onRemove }: { obligation: Obligation; onChange: (patch: Partial<Obligation>) => void; onRemove: () => void }) { const c = calculateCredit(o); const invalid = o.originalPrincipal && o.originalTermMonths ? !obligationSchema.safeParse({ originalPrincipal: o.originalPrincipal, interestRate: o.interestRate ?? 0, originalTermMonths: o.originalTermMonths }).success : false; return <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-2"><input className="min-w-0 flex-1 bg-transparent font-semibold outline-none" value={o.name} onChange={(e) => onChange({ name: e.target.value })}/><span className={`badge ${c.certainty}`}>{c.certainty === "reconstructed" ? "Reconstruido" : c.certainty === "estimated" ? "Estimado" : "Incompleto"}</span><button className="icon-button no-print" onClick={onRemove} aria-label="Eliminar obligación"><Trash2 size={18}/></button></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><Mini label="Capital pendiente" value={money(c.principalOutstanding)}/><Mini label="Intereses" value={money(c.ordinaryInterest)}/><Mini label="Mora" value={money(c.defaultInterest)}/><Mini label="Saldo estimado" value={money(c.calculatedBalance)}/></div><div className="mt-4 border-t border-slate-200 pt-4">
  <p className="section-label">Datos principales</p>
  <div className="form-grid"><label className="field"><span>Tipo</span><select value={o.type} onChange={(e) => onChange({ type: e.target.value as Obligation["type"] })}><option value="creditoConsumo">Crédito de consumo</option><option value="libreInversion">Libre inversión</option><option value="tarjetaCredito">Tarjeta de crédito</option><option value="creditoVehicular">Vehicular</option><option value="creditoHipotecario">Hipotecario</option><option value="libranza">Libranza</option><option value="prestamoParticular">Préstamo particular</option><option value="otro">Otro</option></select></label><Numeric label="Capital original" value={o.originalPrincipal} onChange={(v) => onChange({ originalPrincipal: v })}/><Numeric label="Tasa (%)" value={o.interestRate} onChange={(v) => onChange({ interestRate: v })}/><Numeric label="Plazo (meses)" value={o.originalTermMonths} onChange={(v) => onChange({ originalTermMonths: v })}/></div>
  {invalid && <p className="mt-3 text-xs text-red-700">Revise capital, tasa y plazo.</p>}
  <p className="section-label mt-5">Otros datos (opcionales)</p>
  <div className="form-grid"><label className="field"><span>Fecha de desembolso</span><input type="date" value={o.disbursementDate ?? ""} onChange={(e) => onChange({ disbursementDate: e.target.value })}/></label><label className="field"><span>Tipo de tasa</span><select value={o.interestRateType} onChange={(e) => onChange({ interestRateType: e.target.value as Obligation["interestRateType"] })}><option value="effectiveAnnual">Efectiva anual</option><option value="nominalAnnual">Nominal anual</option><option value="monthly">Mensual</option></select></label><label className="field"><span>Sistema</span><select value={o.amortizationSystem} onChange={(e) => onChange({ amortizationSystem: e.target.value as Obligation["amortizationSystem"] })}><option value="fixedPayment">Cuota fija</option><option value="simpleInterest">Interés simple</option><option value="custom">Personalizado</option></select></label><Numeric label="Cuotas pagadas" value={o.installmentsPaid} onChange={(v) => onChange({ installmentsPaid: v })}/><Numeric label="Total pagado" value={o.totalPaid} onChange={(v) => onChange({ paymentMode: "total", totalPaid: v })}/><Numeric label="Saldo informado" value={o.reportedBalance} onChange={(v) => onChange({ reportedBalance: v })}/><Numeric label="Interés de mora informado" value={o.reportedDefaultInterest} onChange={(v) => onChange({ reportedDefaultInterest: v })}/><Numeric label="Otros conceptos" value={o.reportedOtherCharges} onChange={(v) => onChange({ reportedOtherCharges: v })}/><Numeric label="Días en mora" value={o.daysPastDue} onChange={(v) => onChange({ daysPastDue: v })}/></div>
  {c.warnings.map((w) => <p key={w} className="mt-3 rounded-lg bg-amber-50 p-2 text-xs text-amber-800">{w}</p>)}{c.estimatedInstallment && <p className="mt-3 text-sm">Cuota estimada: <strong>{money(c.estimatedInstallment)}</strong></p>}{c.schedule.length > 0 && <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-cyan-800">Ver tabla de amortización</summary><div className="mt-3 max-h-64 overflow-auto"><table><thead><tr><th>Mes</th><th>Pago</th><th>Interés</th><th>Capital</th><th>Saldo</th></tr></thead><tbody>{c.schedule.map((r) => <tr key={r.month}><td>{r.month}</td><td>{money(r.payment)}</td><td>{money(r.interest)}</td><td>{money(r.principal)}</td><td>{money(r.balance)}</td></tr>)}</tbody></table></div></details>}
  </div></div>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="stat"><p>{label}</p><strong>{value}</strong></div>; } function Breakdown({ label, value }: { label: string; value: number }) { return <div className="flex justify-between py-1.5 text-sm"><span className="text-slate-500">{label}</span><span className="font-medium">{money(value)}</span></div>; } function Mini({ label, value }: { label: string; value: string }) { return <div><p className="text-slate-500">{label}</p><p className="mt-0.5 font-semibold text-slate-800">{value}</p></div>; }
